### ISSUE TITLE
Undefined reference to `__swbuf_r' (and many others) on nightly 2016-10-07

### ISSUE THREAD

**Issue by SimonSapin** [jamesmunns/teensy3-rs#13]
On a recent nightly Rust, linking fails with many "undefined reference" errors. Full output: https://gist.github.com/anonymous/9dad74e99e61647aba6751a0f16b794f

The same output is given if `thumbv7em-none-eabi.json` is removed. Renaming it to something else (like `cortex-m4.json`) and changing `.cargo/config` accordingly works around the issue, so I suspect https://github.com/rust-lang/rust/pull/36874. It looks like passing `--target foo` to Cargo and/or rustc looks for `foo.json` in the current directory, but only if there is no built-in `foo` target in the compiler.

The compiler’s new [`src/librustc_back/target/thumbv7em_none_eabi.rs`](https://github.com/rust-lang/rust/pull/36874/files#diff-dea83515d995b5dce39c6ac884effa86) differs from this repo’s `thumbv7em-none-eabi.json` in several ways, but the most significant here is probably that it doesn’t define any linker arguments.

So the way forward is probably to use the built-in target, and find some other way to pass additional arguments to the linker. (On the other hand, that target already defaults to `arm-none-gcc` for the linker so that’s one fewer line needed in `.cargo/config`.)

**Comment by SimonSapin** [comment]
I’ve tried this in `.cargo/config`:

``` toml
[target.thumbv7em-none-eabi]
rustflags = ["-C", "link-args=-mcpu=cortex-m4 -mthumb -Tteensy3-sys/teensy3-core/mk20dx256.ld -Os -Wl,--gc-sections,--defsym=__rtc_localtime=0 --specs=nano.specs -lm -Wl,--start-group -lnosys -lc -lgcc -Wl,--end-group"]
```

but xargo fails with:

```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name _ --print=file-names -C link-args=-mcpu=cortex-m4 -mthumb -Tteensy3-sys/teensy3-core/mk20dx256.ld -Os -Wl,--gc-sections,--defsym=__rtc_localtime=0 --specs=nano.specs -lm -Wl,--start-group -lnosys -lc -lgcc -Wl,--end-group --sysroot=/home/simon/.xargo --crate-type bin --crate-type rlib --target thumbv7em-none-eabi` (exit code: 101)
--- stderr
error: Unrecognized option: 'm'.
```

In the meantime, I’m using an older nightly with `rustup override set nightly-2016-10-04`.
